spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN:testuser}
    password: ${DB_PASSWORD:123456}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gresdb}